package com.hms.dto;
// default package
// Generated 2015-1-11 18:26:37 by Hibernate Tools 4.0.0

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer adminId;
	private String adminName;
	private String password;
	private int roleId;

	public Admin() {
	}

	public Admin(String adminName, String password, int roleId) {
		this.adminName = adminName;
		this.password = password;
		this.roleId = roleId;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

}
