package com.hms.dto;
// Generated 2015-1-11 18:26:37 by Hibernate Tools 4.0.0

/**
 * CommentReply generated by hbm2java
 */
public class CommentReply implements java.io.Serializable {

	private String commentReplyId;
	private String commendId;
	private String replyContent;
	private int adminId;

	public CommentReply() {
	}

	public CommentReply(String commentReplyId, String commendId,
			String replyContent, int adminId) {
		this.commentReplyId = commentReplyId;
		this.commendId = commendId;
		this.replyContent = replyContent;
		this.adminId = adminId;
	}

	public String getCommentReplyId() {
		return this.commentReplyId;
	}

	public void setCommentReplyId(String commentReplyId) {
		this.commentReplyId = commentReplyId;
	}

	public String getCommendId() {
		return this.commendId;
	}

	public void setCommendId(String commendId) {
		this.commendId = commendId;
	}

	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	public int getAdminId() {
		return this.adminId;
	}

	public void setAdminId(int adminId) {
		this.adminId = adminId;
	}

}
