package com.hms.dto;
// Generated 2015-1-11 18:26:37 by Hibernate Tools 4.0.0

/**
 * CommentReply generated by hbm2java
 */
public class CommentReply implements java.io.Serializable {

	private int commentReplyId;
	private int commendId;
	private String replyContent;
	private int adminId;

	public CommentReply() {
	}

	public CommentReply(int commentReplyId, int commendId,
			String replyContent, int adminId) {
		this.commentReplyId = commentReplyId;
		this.commendId = commendId;
		this.replyContent = replyContent;
		this.adminId = adminId;
	}

	

	public int getCommentReplyId() {
		return commentReplyId;
	}

	public void setCommentReplyId(int commentReplyId) {
		this.commentReplyId = commentReplyId;
	}

	public int getCommendId() {
		return commendId;
	}

	public void setCommendId(int commendId) {
		this.commendId = commendId;
	}

	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	public int getAdminId() {
		return this.adminId;
	}

	public void setAdminId(int adminId) {
		this.adminId = adminId;
	}

}
