package com.hms.dto;
// Generated 2015-1-11 18:26:37 by Hibernate Tools 4.0.0

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private String idCard;
	private String name;
	private String password;
	private int sex;
	private int age;
	private String phone;
	private String email;
	private String address;
	private int status;

	public Customer() {
	}

	public Customer(String idCard, String name, String password, int sex,
			int age, String phone, String email, String address, int status) {
		this.idCard = idCard;
		this.name = name;
		this.password = password;
		this.sex = sex;
		this.age = age;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.status = status;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getSex() {
		return this.sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
