package com.hms.dto;
// Generated 2015-1-11 18:26:37 by Hibernate Tools 4.0.0

/**
 * NewType generated by hbm2java
 */
public class NewType implements java.io.Serializable {

	private int id;
	private String name;
	private String descr;

	public NewType() {
	}

	public NewType(int id, String name, String descr) {
		this.id = id;
		this.name = name;
		this.descr = descr;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

}
