package com.hms.dto;
// Generated 2015-1-11 18:26:37 by Hibernate Tools 4.0.0

/**
 * Predetemine generated by hbm2java
 */
public class Predetemine implements java.io.Serializable {

	private String predetermineId;
	private String idCard;
	private long presetTime;
	private int roomType;
	private int number;
	private int price;
	private String customerIdCard;
	private String customerName;
	private String phone;
	private long checkInTime;
	private long checkOutTime;
	private int status;

	public Predetemine() {
	}

	

	public int getPrice() {
		return price;
	}



	public void setPrice(int price) {
		this.price = price;
	}



	public String getPredetermineId() {
		return this.predetermineId;
	}

	public void setPredetermineId(String predetermineId) {
		this.predetermineId = predetermineId;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public int getRoomType() {
		return this.roomType;
	}

	public void setRoomType(int roomType) {
		this.roomType = roomType;
	}

	public int getNumber() {
		return this.number;
	}
    
	
	public String getPhone() {
		return phone;
	}



	public void setPhone(String phone) {
		this.phone = phone;
	}



	public void setNumber(int number) {
		this.number = number;
	}

	public String getCustomerIdCard() {
		return this.customerIdCard;
	}

	public void setCustomerIdCard(String customerIdCard) {
		this.customerIdCard = customerIdCard;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

    
	
	
	public long getPresetTime() {
		return presetTime;
	}



	public void setPresetTime(long presetTime) {
		this.presetTime = presetTime;
	}



	public long getCheckInTime() {
		return checkInTime;
	}



	public void setCheckInTime(long checkInTime) {
		this.checkInTime = checkInTime;
	}



	public long getCheckOutTime() {
		return checkOutTime;
	}



	public void setCheckOutTime(long checkOutTime) {
		this.checkOutTime = checkOutTime;
	}



	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
