package com.hms.dto;
// Generated 2015-1-11 18:26:37 by Hibernate Tools 4.0.0

/**
 * Predetemine generated by hbm2java
 */
public class Predetemine implements java.io.Serializable {

	private String predetermineId;
	private String idCard;
	private String presetTime;
	private int roomType;
	private int number;
	private String customerIdCard;
	private String customerName;
	private String checkInTime;
	private String checkOutTime;
	private int status;

	public Predetemine() {
	}

	public Predetemine(String predetermineId, String idCard, String presetTime,
			int roomType, int number, String customerIdCard,
			String customerName, String checkInTime, String checkOutTime,
			int status) {
		this.predetermineId = predetermineId;
		this.idCard = idCard;
		this.presetTime = presetTime;
		this.roomType = roomType;
		this.number = number;
		this.customerIdCard = customerIdCard;
		this.customerName = customerName;
		this.checkInTime = checkInTime;
		this.checkOutTime = checkOutTime;
		this.status = status;
	}

	public String getPredetermineId() {
		return this.predetermineId;
	}

	public void setPredetermineId(String predetermineId) {
		this.predetermineId = predetermineId;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getPresetTime() {
		return this.presetTime;
	}

	public void setPresetTime(String presetTime) {
		this.presetTime = presetTime;
	}

	public int getRoomType() {
		return this.roomType;
	}

	public void setRoomType(int roomType) {
		this.roomType = roomType;
	}

	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public String getCustomerIdCard() {
		return this.customerIdCard;
	}

	public void setCustomerIdCard(String customerIdCard) {
		this.customerIdCard = customerIdCard;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCheckInTime() {
		return this.checkInTime;
	}

	public void setCheckInTime(String checkInTime) {
		this.checkInTime = checkInTime;
	}

	public String getCheckOutTime() {
		return this.checkOutTime;
	}

	public void setCheckOutTime(String checkOutTime) {
		this.checkOutTime = checkOutTime;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
