package com.hms.dto;
// Generated 2015-1-11 18:26:37 by Hibernate Tools 4.0.0

/**
 * Registration generated by hbm2java
 */
public class Registration implements java.io.Serializable {

	private String id;
	private int roomId;
	private int roomType;
	private long checkInTime;
	private long checkOutTime;
	private String customerIdCard;
	private String customerName;
	private String predetermineId;
	private int day;
	private int cost;
	private int margin;
	private int checkInAdmin;
	private int checkOutAdmin;
	private int status;

	public Registration() {
	}

	

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getRoomId() {
		return this.roomId;
	}

	public void setRoomId(int roomId) {
		this.roomId = roomId;
	}

	

	public int getRoomType() {
		return roomType;
	}



	public void setRoomType(int roomType) {
		this.roomType = roomType;
	}



	public long getCheckInTime() {
		return checkInTime;
	}



	public void setCheckInTime(long checkInTime) {
		this.checkInTime = checkInTime;
	}



	public long getCheckOutTime() {
		return checkOutTime;
	}



	public void setCheckOutTime(long checkOutTime) {
		this.checkOutTime = checkOutTime;
	}



	public String getCustomerIdCard() {
		return this.customerIdCard;
	}

	public void setCustomerIdCard(String customerIdCard) {
		this.customerIdCard = customerIdCard;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getPredetermineId() {
		return this.predetermineId;
	}

	public void setPredetermineId(String predetermineId) {
		this.predetermineId = predetermineId;
	}

	public int getDay() {
		return this.day;
	}

	public void setDay(int day) {
		this.day = day;
	}

	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	public int getMargin() {
		return this.margin;
	}

	public void setMargin(int margin) {
		this.margin = margin;
	}

	public int getCheckInAdmin() {
		return this.checkInAdmin;
	}

	public void setCheckInAdmin(int checkInAdmin) {
		this.checkInAdmin = checkInAdmin;
	}

	public int getCheckOutAdmin() {
		return this.checkOutAdmin;
	}

	public void setCheckOutAdmin(int checkOutAdmin) {
		this.checkOutAdmin = checkOutAdmin;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
