package com.hms.dto;

import java.util.Set;
// Generated 2015-1-11 18:26:37 by Hibernate Tools 4.0.0

/**
 * RoomType generated by hbm2java
 */
public class RoomType implements java.io.Serializable {

	private int id;
	private String type;
	private int price;
	private int discountPrice;
	private int bedNumber;
    private Set<RoomTypeImage> roomTypeImages;
	public RoomType() {
	}

	public RoomType(int id, String type, int price, int discountPrice,
			int bedNumber) {
		this.id = id;
		this.type = type;
		this.price = price;
		this.discountPrice = discountPrice;
		this.bedNumber = bedNumber;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getDiscountPrice() {
		return this.discountPrice;
	}

	public void setDiscountPrice(int discountPrice) {
		this.discountPrice = discountPrice;
	}

	public int getBedNumber() {
		return this.bedNumber;
	}

	public void setBedNumber(int bedNumber) {
		this.bedNumber = bedNumber;
	}

	public Set<RoomTypeImage> getRoomTypeImages() {
		return roomTypeImages;
	}

	public void setRoomTypeImages(Set<RoomTypeImage> roomTypeImages) {
		this.roomTypeImages = roomTypeImages;
	}
	

}
