package com.hms.dto;
// Generated 2015-1-11 18:26:37 by Hibernate Tools 4.0.0

/**
 * NewType generated by hbm2java
 */
public class Setting implements java.io.Serializable {

	private int id;
	private String key;
	private String value;

	public Setting() {
	}

	public Setting(int id, String key, String value) {
		this.id = id;
		this.key = key;
		this.value = value;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getKey() {
		return this.key;
	}

	public void setName(String key) {
		this.key = key;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
